import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/Redux/provider";
import "./globals.css";
import { AuthProvider } from "./Common/Context/AuthContext";
import { CartProvider } from "./Common/Context/CartContext";
import LayoutWrapper from "./Components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Easy Shop",
  description: "Generated by create next app",
  icons: {
    icon: "/websitelogo-circle.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-brand-cream`}>
       <ReduxProvider>
        <AuthProvider>
          <CartProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </CartProvider>
        </AuthProvider>
       </ReduxProvider>
      </body>
    </html>
  );
}
