import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/Redux/provider";
import "./globals.css";
import { AuthProvider } from "./Common/Context/AuthContext";
import { CartProvider } from "./Common/Context/CartContext";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
       <ReduxProvider>
        <AuthProvider>
          <CartProvider>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </CartProvider>
        </AuthProvider>
       </ReduxProvider>
      </body>
    </html>
  );
}
